import pandas as pd
import numpy as np
print('Comprar un buen café es una experiencia única.')
print('El aroma, el sabor y la textura son inigualables.')
print('¿Qué tipo de café prefieres?')
print('1. Espresso')
print('2. Americano')
print('3. Latte')
print('4. Cappuccino')
print('5. Mocha')
print('6. Macchiato')
print('7. Cortado')
print('8. Affogato')
print('9. Ristretto')
print('10. Flat White')
print('11. Cold Brew')
print('12. Nitro Cold Brew')
print('13. Irish Coffee')
print('14. Dalgona Coffee')